[workspace]
members = [
  "cassis-core",
  "cassis-keys",
  "cassis-routing",
  "cassis-iroh",
  "networks/cassis-cashu",
  "networks/cassis-fedimint",
  "networks/cassis-arkade",
  "networks/cassis-rootstock",
  "networks/cassis-liquid",
  "cassis-router",
  "cassis-client",
  "cassis-cli",
  "cassis-gui",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
