[package]
name = "rust-cassis"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
byteorder = "1.5.0"
lazy_static = "1.4.0"
redb = "2.1.0"
rkyv = "0.7.44"
serde = { version = "1.0.199", features = ["derive"] }
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
