[package]
name = "cassis-iroh"
version.workspace = true
edition.workspace = true

[dependencies]
cassis-core = { workspace = true }
lowercase-hex = { workspace = true }
iroh = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "sync"] }
tracing = { workspace = true }
