[package]
name = "cassis-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
cassis = { path = "../lib" }
tokio = { workspace = true }
hex = { workspace = true }
secp256k1 = { workspace = true }
serde_json = { workspace = true }
clap = "4.5.4"
reqwest = "0.12.4"
