[package]
name = "cassis-core"
version.workspace = true
edition.workspace = true

[features]
cashu = []
liquid = []
arkade = []
rootstock = []

[dependencies]
async-trait = { workspace = true }
lowercase-hex = { workspace = true, features = ["alloc"] }
rand = { workspace = true }
ritualistic = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
