[package]
name = "cassis-router"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
cassis-core = { workspace = true }
cassis-iroh = { workspace = true }
cassis-keys = { workspace = true }
cassis-routing = { workspace = true }
iroh = { workspace = true }
lowercase-hex = { workspace = true }
ritualistic = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "sync"] }
tracing = { workspace = true }

[dependencies.cassis-cashu]
workspace = true
optional = true

[dependencies.cassis-arkade]
workspace = true
optional = true

[dependencies.cassis-rootstock]
workspace = true
optional = true

[dependencies.cassis-liquid]
workspace = true
optional = true

[dependencies.cassis-lightning]
workspace = true
optional = true

[features]
arkade = ["dep:cassis-arkade", "cassis-core/arkade"]
cashu = ["dep:cassis-cashu", "cassis-core/cashu"]
liquid = ["dep:cassis-liquid", "cassis-core/liquid"]
rootstock = ["dep:cassis-rootstock", "cassis-core/rootstock"]
lightning = ["dep:cassis-lightning", "cassis-core/lightning"]
