[package]
name = "cassis-routing"
version.workspace = true
edition.workspace = true

[dependencies]
cassis-core = { workspace = true }
ritualistic = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = { workspace = true }
