[package]
name = "cassis-client"
version.workspace = true
edition.workspace = true

[features]
default = []
cashu = ["cassis-core/cashu"]
arkade = ["dep:cassis-arkade", "cassis-core/arkade"]
bitcoin = ["dep:cassis-bitcoin", "cassis-core/bitcoin"]
liquid = ["dep:cassis-liquid", "cassis-core/liquid"]
rootstock = ["cassis-core/rootstock"]
fedimint = ["dep:cassis-fedimint"]
lightning = ["dep:cassis-lightning", "cassis-core/lightning"]

[dependencies]
cassis-core = { workspace = true, features = ["cashu", "rootstock"] }
cassis-keys = { workspace = true }
cassis-routing = { workspace = true }
cassis-iroh = { workspace = true }
cassis-router = { workspace = true }
cassis-cashu = { workspace = true }
cassis-rootstock = { workspace = true }
cassis-fedimint = { workspace = true, optional = true }
cassis-arkade = { workspace = true, optional = true }
cassis-bitcoin = { workspace = true, optional = true }
cassis-liquid = { workspace = true, optional = true }
cassis-lightning = { workspace = true, optional = true }
clap = { workspace = true }
futures = { workspace = true }
iroh = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "process", "time", "fs", "io-util", "net"] }
minisqlite = { workspace = true }
tracing = { workspace = true }
